# AnalyticsExample

use_frameworks!
platform :ios, '10.0'

target 'AnalyticsExample' do
  pod 'Firebase/Analytics'
  pod 'FSAdSDK/Banner'
  pod 'Google-Mobile-Ads-SDK', '7.50.0'
  
  target 'AnalyticsExampleTests' do
    inherit! :search_paths
  end
end

target 'AnalyticsExampleSwift' do
  pod 'Firebase/Analytics'
  pod 'FSAdSDK/Banner'
  pod 'Google-Mobile-Ads-SDK', '7.50.0'
  pod 'SnapKit', '~> 5.0.0'
end
